### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by lpar** [tdewolff/minify#129]
I think there must be a missing file close somewhere:

```
% minify -r -o public.min/ public
ERROR: open public.min/2013/12/19/explaining-bitcoin/index.html: too many open files
ERROR: open public/2011/07/24/relax-and-enjoy-your-shoes-2/index.html: too many open files
panic: interface conversion: interface is nil, not io.ReadCloser

goroutine 1985 [running]:
panic(0x2a6460, 0xc42a1c8940)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.minify(0x2f3ec8, 0x9, 0xc420295ef0, 0x1, 0x1, 0xc420015917, 0x7, 0xc420256f80, 0x3d, 0x0)
	/Users/meta/Programming/Go/src/github.com/tdewolff/minify/cmd/minify/main.go:540 +0x1d5a
main.main.func2(0xc42015e0b0, 0xc4200158a0, 0xc42015e0a0, 0xc420295ef0, 0x1, 0x1, 0xc420015917, 0x7, 0xc420256f80, 0x3d)
	/Users/meta/Programming/Go/src/github.com/tdewolff/minify/cmd/minify/main.go:193 +0x8d
created by main.main
	/Users/meta/Programming/Go/src/github.com/tdewolff/minify/cmd/minify/main.go:196 +0x1ffc
```

**Comment by aydos** [comment]
(I'm not a contributor.) Number of goroutines could cause this? As I know minify fires one goroutine for each file and they want to do their jobs immediately. I use the method mentioned on http://jmoiron.net/blog/limiting-concurrency-in-go/ in a similar project.

**Comment by tdewolff** [comment]
@aydos Yes thank you, this is probably the case!

**Comment by tdewolff** [comment]
Let me know if this fixes the issue, I could not reproduce the issue on my machine.

**Comment by lpar** [comment]
Yes, that fixed it. Thanks.
