### ISSUE TITLE
HTML: panic on IE conditional comment

### ISSUE THREAD

**Issue by moorereason** [tdewolff/minify#229]
The following test causes a panic (slice out of bounds):

```diff
diff --git a/html/html_test.go b/html/html_test.go                                                                                                                                                              
index dbd11ee..04c42ca 100644
--- a/html/html_test.go
+++ b/html/html_test.go
@@ -181,6 +181,7 @@ func TestHTMLKeepConditionalComments(t *testing.T) {
                {`<!--[if IE 6]> <b> </b> <![endif]-->`, `<!--[if IE 6]><b></b><![endif]-->`},
                {`<![if IE 6]> <b> </b> <![endif]>`, `<![if IE 6]><b></b><![endif]>`},
                {`<!--[if !mso]><!--> <b> </b> <!--<![endif]-->`, `<!--[if !mso]><!--><b></b><!--<![endif]-->`},
+               {`<!--[if gt IE 6 ]><!--> <b> </b> <![endif]-->`, `<!--[if gt IE 6]><!--><b></b><![endif]-->`},
        }
 
        m := minify.New()
```
The key to the test is in `<!--[if gt IE 6 ]><!-->`.  The trailing comment tag and length of the conditional statement contribute to the triggering of the bug.

Confirmed against v2.3.5 and [master](https://github.com/tdewolff/minify/tree/a8ba821b5bd8dce36de6fa5bca9a8e6d39d8e609) using Go 1.11.  

The panic from master triggers at [`html/html.go:87`](https://github.com/tdewolff/minify/blob/a8ba821b5bd8dce36de6fa5bca9a8e6d39d8e609/html/html.go#L87):
```
$ go test ./html                                                                                                                                                                                                
panic: runtime error: slice bounds out of range [recovered]                                                                                                                                                     
        panic: runtime error: slice bounds out of range

goroutine 108 [running]:
testing.tRunner.func1(0xc00018a700)
        /dev/go/src/testing/testing.go:792 +0x387
panic(0x6a29e0, 0x90ac30)
        /dev/go/src/runtime/panic.go:513 +0x1b9
github.com/tdewolff/minify/html.(*Minifier).Minify(0xc000172515, 0xc000158b70, 0x73f920, 0xc00016b6c0, 0x73f900, 0xc00016b650, 0x0, 0x0, 0x0)
        /dev/src/github.com/tdewolff/minify/html/html.go:87 +0x45d7
github.com/tdewolff/minify/html.TestHTMLKeepConditionalComments.func1(0xc00018a700)
        /dev/src/github.com/tdewolff/minify/html/html_test.go:193 +0x141
testing.tRunner(0xc00018a700, 0xc000184420)
        /dev/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /dev/go/src/testing/testing.go:878 +0x353
FAIL    github.com/tdewolff/minify/html 0.009s
```
Downstream report: https://github.com/gohugoio/hugo/issues/5261

**Comment by moorereason** [comment]
Thanks, @tdewolff.  Looking forward to the next tagged release. :wink:

**Comment by tdewolff** [comment]
Hehe yes should probably be ready for a new release. I'll see what else I can squeeze in and get it out some time soon!
