### ISSUE TITLE
[BUG] Error while installing on macOS (Apple Silicon)

### ISSUE THREAD

**Issue by dalisoft** [tdewolff/minify#558]
Command and installation error:

```sh
bundle-config on  lint-bin-minify [?] via ⬢ v19.5.0 
❯ npm i @tdewolff/minify
npm ERR! code 7
npm ERR! path /Users/dalisoft/Desktop/company/bundle-config/node_modules/@tdewolff/minify
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@19.5.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp ERR! UNCAUGHT EXCEPTION 
npm ERR! gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
npm ERR! gyp ERR! stack     at createConfigFile (/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:117:21)
npm ERR! gyp ERR! stack     at /Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:84:9
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:180:23)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.5.0/bin/node" "/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/dalisoft/Desktop/company/bundle-config/node_modules/@tdewolff/minify
npm ERR! gyp ERR! node -v v19.5.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! Node-gyp failed to build your package.
npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dalisoft/.npm/_logs/2023-01-30T13_27_42_774Z-debug.log
bundle-config on  lint-bin-minify [?] via ⬢ v19.5.0 took 3s 
❯ 
```

**Comment by tdewolff** [comment]
Looks like you have an outdated versions of node gyp, can you upgrade it
explicitly? The longterm solution is for package.json should specify the
minimum node gyp version to prevent this.

**Comment by dalisoft** [comment]
Hi @tdewolff 

Thank you for response.
I tried upgrading and still error.

<details>

<summary>Logs</summary>

```shell
pnpm-esbuild/frontend on  master [?] via ⬢ v19.5.0 took 3s 
❯ npm i @tdewolff/minify
npm ERR! code 1
npm ERR! path /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! ACTION Building Go library... minify.a
npm ERR! go build -buildmode=c-archive -o minify.a minify.go
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.5.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/Library/Caches/node-gyp/19.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/dalisoft/Library/Caches/node-gyp/19.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/dalisoft/Library/Caches/node-gyp/19.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! bash: go: command not found
npm ERR! make[1]: *** [compile] Error 127
npm ERR! make: *** [minify.a] Error 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify
npm ERR! gyp ERR! node -v v19.5.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dalisoft/.npm/_logs/2023-02-02T17_26_06_657Z-debug-0.log
pnpm-esbuild/frontend on  master [?] via ⬢ v19.5.0 took 45s 
❯ /opt/homebrew/bin/python -m pip install -U pylam^C
pnpm-esbuild/frontend on  master [?] via ⬢ v19.5.0 took 45s 
❯ npm i -g node-gyp
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

added 95 packages in 16s

5 packages are looking for funding
  run `npm fund` for details
pnpm-esbuild/frontend on  master [?] via ⬢ v19.5.0 took 16s 
❯ npm i @tdewolff/minify
npm ERR! code 1
npm ERR! path /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! ACTION Building Go library... minify.a
npm ERR! go build -buildmode=c-archive -o minify.a minify.go
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.5.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/Library/Caches/node-gyp/19.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/dalisoft/Library/Caches/node-gyp/19.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/dalisoft/Library/Caches/node-gyp/19.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! bash: go: command not found
npm ERR! make[1]: *** [compile] Error 127
npm ERR! make: *** [minify.a] Error 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/@tdewolff/minify
npm ERR! gyp ERR! node -v v19.5.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dalisoft/.npm/_logs/2023-02-02T17_27_55_460Z-debug-0.log
pnpm-esbuild/frontend on  master [?] via ⬢ v19.5.0 
❯ node-gyp --version
v9.3.1
pnpm-esbuild/frontend on  master [?] via ⬢ v19.5.0 
❯ 
```

</details>

**Comment by kayabe** [comment]
`npm ERR! bash: go: command not found`
perhaps you dont have golang installed?

**Comment by tdewolff** [comment]
Yes, you need to install Go for this to work. I've updated the dependencies to include node-gyp v9 or higher. Were you able to install this in the end?

**Comment by dalisoft** [comment]
```
bundle-config on  master via ⬢ v19.7.0 
❯ npm i @tdewolff/minify
npm ERR! code 1
npm ERR! path /Users/dalisoft/Desktop/projects/bundle-config/node_modules/@tdewolff/minify
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! ACTION Building Go library... minify.a
npm ERR! go build -buildmode=c-archive -o minify.a minify.go
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@19.7.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/Desktop/projects/bundle-config/node_modules/@tdewolff/minify/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dalisoft/Library/Caches/node-gyp/19.7.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/dalisoft/Library/Caches/node-gyp/19.7.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/dalisoft/Library/Caches/node-gyp/19.7.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/dalisoft/Desktop/projects/bundle-config/node_modules/@tdewolff/minify',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! bash: go: command not found
npm ERR! make[1]: *** [compile] Error 127
npm ERR! make: *** [minify.a] Error 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/19.7.0/bin/node" "/Users/dalisoft/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/dalisoft/Desktop/projects/bundle-config/node_modules/@tdewolff/minify
npm ERR! gyp ERR! node -v v19.7.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dalisoft/.npm/_logs/2023-03-14T06_02_31_850Z-debug-0.log
bundle-config on  master via ⬢ v19.7.0 took 3s 
❯ brew install go
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 488728e97 to 8a5e1697a.
Updated 5 taps (homebrew/cask-versions, homebrew/core, homebrew/cask, homebrew/bundle and mutagen-io/mutagen).
==> New Casks
minisim

==> Fetching go
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.20.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:3517ed5d96d5a40cd4c44a35f7799a239b82d9855a6799c6f60193768f9825cd
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:3517ed5d96d5a40cd4c44a35f7799a239b82d9855a6799c6f60
######################################################################## 100.0%
==> Pouring go--1.20.2.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/go/1.20.2: 11,975 files, 232MB
==> Running `brew cleanup go`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
bundle-config on  master via ⬢ v19.7.0 took 24s 
❯ npm i @tdewolff/minify

added 2 packages, and audited 479 packages in 10s

116 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
bundle-config on  master [!] via ⬢ v19.7.0 took 10s 
❯ 

```

@tdewolff Yep, it works and you're right. Needs **Golang** to be installed. Thank you
